name: CI

on:
  push:
    branches: [main]

jobs:
  x86_64-linux:
    runs-on: self-hosted-x86_64-linux
    steps:
      - name: repository checkout
        uses: actions/checkout@v4
      - name: build hosts configuration
        run: ./.ci.sh

  aarch64-linux:
    runs-on: self-hosted-aarch64-linux
    steps:
      - name: repository checkout
        uses: actions/checkout@v4
      - name: build hosts configuration
        run: ./.ci.sh
