# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }:
let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "bed63f6dae0879ac840066b031229e0d139089cd";
    sha256 = "17q9aqpp8b9haxx6hp4l5z38isirbn86d7p54bz8m6p3iy030sqp";
  };
in applyPatches {
  inherit src;
  patches = [ ./local-new-fixes.patch ];
}
