# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "329863073982a561f9d10a81af83581094da0417";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "arachnist";
      repo = "mastodon";
      rev = "${version}";
      hash = "sha256-DEc0oXpPU2FevdAthrZ9ZVERkujFS03qx8wvlGvdNCw=";
    };
    patches = patches ++ [./local-new-fixes.patch];
  }) // {
  inherit version;
  yarnHash = "sha256-P7KswzsCusyiS4MxUFnC1HYMTQ6fLpIwd97AglCukIk=";
}
