# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches }:
let
  src = fetchFromGitHub {
    owner = "arachnist";
    repo = "mastodon";
    rev = "e4e18e4f9fc062cd347bb2faa719ad2f62660bfd";
    hash = "sha256-k5ZO+x7MzQaHShViBltmrCoy5wujKXIsQvPTpWgkvUk=";
  };
in applyPatches {
  inherit src;
  patches = [ ./local-new-fixes.patch ];
}
