# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "";
in
applyPatches {
  inherit version;
  src = fetchFromGitHub {
    owner = "arachnist";
    repo = "mastodon";
    rev = "161a19f3aa8d9fa40ae2a08fdb81e42939ae32dd";
    hash = "sha256-zPK7HEDYfKLlrFB9VwLxWJSCSbP4VPWzaO3H37hrGG0=";
  };
  patches = [./local-new-fixes.patch];
  yarnHash = "sha256-P7KswzsCusyiS4MxUFnC1HYMTQ6fLpIwd97AglCukIk=";
}
