#!/usr/bin/ruby
require 'json'
require 'yaml'
require 'pp'

config = YAML.load_file(ARGV[0])
def update_translations(hash, replacements)
    hash.reduce({}) do |acc, (key,value)|
        if value.is_a?(Hash)
            acc[key] = update_translations(value, replacements)
        elsif value.is_a?(String)
            replacements.to_a.sort_by do |x| 0-x[0].length end.each do |from, to|
                if value.match?(from) then
                    value.gsub!(from, to)
                end
            end
            acc[key] = value
        end
        acc
    end
end

config["paths"].each do |dir|
    Dir.entries(dir).each do |fname|
        config["replacements"].each do |lang, conf|
            conf["filename-patterns"].each do |pattern|
                if File.fnmatch?(pattern, fname) then
                    config["types"]["yaml"].each do |type_ext|
                        if File.extname(fname) == type_ext then
                            fpath = File.join(dir, fname)
                            puts " .... updating #{fpath}"
                            tl = YAML.load_file(fpath)
                            tl = update_translations(tl, conf["strings"])

                            File.open(fpath, 'w') do |file|
                                file.write(tl.to_yaml(options = {:line_width => -1}))
                            end
                        end
                    end

                    config["types"]["json"].each do |type_ext|
                        if File.extname(fname) == type_ext then
                            fpath = File.join(dir, fname)
                            puts " .... updating #{fpath}"
                            tl = JSON.load_file(fpath)
                            tl = update_translations(tl, conf["strings"])

                            File.open(fpath, 'w') do |file|
                                file.write(JSON.pretty_generate(tl))
                            end
                        end
                    end
                end
            end
        end
    end
end
